### PR TITLE
Milestone5

### PR DESCRIPTION
**Pull request by Paul-Clue**
## What I Did:
- I followed the zeplin design specs and built a user interface for the bookstore app.

### CODE REVIEW

**Review by eliasecasta — CHANGES_REQUESTED** [review]
# Status:  Changes Required ♻️
_Check the comments under the review_
<hr>

Hello @Paul-Clue, I am Elias, your reviewer for this PR

Well done so far with your project!

You did not forget any element in your design part of this project, great job!

I will mention to you a small summary of things that need to be changed in order to keep moving:

- [ ] Styling is **EXACTLY** the same as the one provided in the designs ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone5/exactlySameAsDesign.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/45791599/))
(Your main container is not centered in your webpage, if I zoom out a little bit you can see that everything goes to the left instead that keeping itself in the center, please fix this to comply with the design provided): 
image
- [ ] In the stylesheets of the app, make sure that basic CSS bad practices are not used ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
  - No repeating of the same rule

(Please make use of CSS classes to avoid CSS rules repetition like for example your custom colors repeated like ```#e8e8e8``` among others, your montserrat sans serif font family among others like the roboto, and these rules which are repeated a lot through your CSS files):
image

- [ ] You are missing to add a placeholder to the book title input as well as gray out both the title and category placeholders, please do so to make your app look exactly as the design provided:
Your design:
image

Provided one:
image

Please correct those issues and send another review request, good luck, and well done so far! 

Code review by Elias Castañeda

_(Feel free to leave any questions or comments in the PR thread if something is not 100% clear)_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Paul-Clue** [comment]
I fixed all of the issues that the last reviewer spoke about. However, I did not refactor all of the style sheets of this project. I followed the instructions of the project and copied the styling from the website. The instructions did not say to refactor the styling. Please refactoring the styling would be a complete waste of my time. The website is a professional site. That is how they wrote the code and that is how I copied it, following the directions from the pathwright. Once again, please consider how much of a minor issue this is compared to the amount of time it is going to take to do something that is not necessary. I fixed all of the other real issues from the review. The css code is the code from the zeplin website used to build the UI and that is the code I used according to the instructions of the pathwright.

**Comment by bellom** [comment]
@Paul-Clue, Sorry if things ain't the way you want but we are all here to learn, not just learn but learn the right things and improve.

Yes, you used the zeplin design, but that was just a design sample, and also we always there is always room for improvement.

I'm sure you're aware that code reviewers won't just ask you to ask for changes if it is not in the review guidelines which Microverse team created, so if you're saying you can't then you're saying you don't want to follow microverse project requirement, as you can see the screenshot below is coming from the pathwright. 👇 
image

To be fair to other students and to make your repo looks professional, you might want to remove the CSS bad practice, in fact, the goal is to learn and get a job and reflect the learning, from my experience 🙂 recruiters will always go for a codebase with minimal bad practice.



> I fixed all of the issues that the last reviewer spoke about. However, I did not refactor all of the style sheets of this project. I followed the instructions of the project and copied the styling from the website. The instructions did not say to refactor the styling. Please refactoring the styling would be a complete waste of my time. The website is a professional site. That is how they wrote the code and that is how I copied it, following the directions from the pathwright. Once again, please consider how much of a minor issue this is compared to the amount of time it is going to take to do something that is not necessary. I fixed all of the other real issues from the review. The css code is the code from the zeplin website used to build the UI and that is the code I used according to the instructions of the pathwright.

**Review by bellom — CHANGES_REQUESTED** [review]
## Hi @Paul-Clue   :clap: 

**Great work making `almost` all the necessary corrections from the previous review.**

# Status: Changes Required! ♻️ 

I wish I could use inline comments but the changes ain't on this PR.

Example:

In `Book.css`

You have `display: flex` all over, which is repetition of rule;

You could have this way;
```
.card, bookActions, completed {
    display: flex
}
```
Kindly do this for all repeated rules.

**Kindly check out my comment above this review;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Hi, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️

- [ ] As previous CR said, make sure that basic CSS bad practices are not used ([article for support](https://speckyboy.com/good-bad-css-practices) ) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

- No repeating of the same rule
In your **BookList.css** for example, you still have so many repeated rules like

```CSS
  font-style: normal;
  line-height: normal;
  display: flex;
```

- [ ] Please, make sure that Github action is running. No PR should be approved if it is not running. Keep in mind that it will check your code automatically.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Paul-Clue** [comment]
To the next code reviewer, look here:
fix
I already fixed what Bellom asked me to fix. I do not know why Rindrajosia did not see this. Also the head code reviewer wrote this:
feedback
The head code reviewer saw that I made the proper changes.

**Review by taiwo2 — APPROVED** [review]
# STATUS: APPROVED 🎉 
@Paul-Clue Congratulations on this project and thanks for implementing the suggested changes by all the previous Code Reviewer, I commend your Efforts. it's time to merge 🥂 🥂

**Comment by rindrajosia** [comment]
> To the next code reviewer, look here:
> fix
> I already fixed what Bellom asked me to fix. I do not know why Rindrajosia did not see this. Also the head code reviewer wrote this:
> feedback
> The head code reviewer saw that I made the proper changes.

You have made this change in the book.css not in the bokkList.css

**Pull request merged**
